extends:
  - '@digitallinguistics/eslint-config'
  - plugin:chai-friendly/recommended
  - plugin:cypress/recommended

env:
  mocha: true
  shared-node-browser: true

plugins:
  - chai-friendly
  - cypress

overrides:
  - files:
      - '**/*.component.*'
      - '**/*.e2e.*'
      - '**/*.test.*'
      - '**/*.unit.*'
    globals:
      expect: on
    rules:
      func-names:            off
      prefer-arrow-callback: off
      max-nested-callbacks:  off
      max-params:            off
      no-magic-numbers:      off
      no-param-reassign:     off
      no-unused-expressions: off
      chai-friendly/no-unused-expressions: error