name: tests

on:
  pull_request:
    branches:
      - main

jobs:

  run-tests:
    name:    run tests
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: cache Node.js modules
        id:   cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key:  ${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run:  npm install

      - name: run stop-only test
        run:  npm run stop-only

      - name: build app
        run:  npm run build --if-present

      - name: run tests
        run:  npm test