name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  COSMOS_ENDPOINT: https://localhost:8081
  COSMOS_KEY:      C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw== # well-known key for Cosmos DB emulator
  LOGGING:         TRUE
  MS_AUTH_COOKIE:  AppServiceAuthSession
  MS_AUTH_HEADER:  X-MS-CLIENT-PRINCIPAL-NAME
  MS_AUTH_USER:    owner@digitallinguistics.io
  NODE_ENV:        CI
  PORT:            3001

jobs:

  run-tests:
    name:    run tests
    runs-on: windows-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: cache Node.js modules
        id:   cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key:  ${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run:  npm install

      - name: run stop-only test
        run:  npm run stop-only

      - name: build app
        run:  npm run build --if-present

      - name: start database
        uses: southpolesteve/cosmos-emulator-github-action@v1

      - name: run tests
        run:  npm test